// react-js/src/components/Graph/Graph.js
import React from 'react'
import './Graph.css'
import { GraphClass } from './GraphTypes.js';
import ConfigPanel from '../ConfigPanel/ConfigPanel';
import IconGear from '../../images/icon-gear.js';
// import IconLogo from '../../images/icon-logo.tsx';

let myGraph = null;
let configPanelStyle = {};

const Graph = ({ strengths, width, data, dataset }) => {
  const [configSelected, setConfigSelected] = React.useState(false);
  const [nodeCount, setNodeCount] = React.useState(0);
  const [edgeCount, setEdgeCount] = React.useState(0);

  React.useEffect(() => {
    if (data) {
      myGraph = new GraphClass({
        component: document.getElementById(`graph-wrapper`),
        data,
        strengths,
        width,
        height: width
      });

      setNodeCount(data.nodes.length);
      setEdgeCount(data.links.length);
    }
    const panelRoom = Math.floor((window.innerWidth - width) / 2);
    if (panelRoom < 190) {
      configPanelStyle = {
        transform: `translateX(calc(100% - ${190 - panelRoom + 5}px))`,
        top: '42px'
      }
    }
  }, [data, strengths, width, dataset.file]);
      
  return (    
    <div className="graph-wrapper" style={{ width: width, height: width }} id={`graph-wrapper`}>
    <svg className="graph-svg" />

    <div className="graph-footer">
        <span>{`${nodeCount} nodes, ${edgeCount} edges`}</span>
        <a href="https://github.com/poloclub/nova" target="_blank" rel="noreferrer">
            <span className="name">
                {/* <IconLogo /> */}
            </span>
        </a>
    </div>

    <div
        className={`config-button ${configSelected ? 'selected' : ''}`}
        onClick={() => {
            setConfigSelected(!configSelected);
        }}
    >
        <IconGear />
    </div>
    <div
      className={`config-container ${!configSelected ? 'no-display' : ''}`}
      style={ configPanelStyle }
    >
        <ConfigPanel height={width} myGraph={myGraph} flipConfigSelected={() => setConfigSelected(!configSelected)} />
    </div>
    </div>
  )
}

export default Graph;

// svelte/src/components/graph/Graph.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Graph } from './Graph';
  import type { GraphData, Strengths } from './Graph';
  import ConfigPanel from '../config-panel/ConfigPanel.svelte';
  import d3 from '../../d3-imports';
  import iconSetting from '../../images/icon-gear.svg?raw';

  export let modelFile: string | null = null;
  export let strengths: Strengths | null = null;
  export let width: number = 600;

  let myGraph: Graph | null = null;
  let component: HTMLElement | null = null;
  let initialized = false;
  let mounted = false;

  let nodeCount = 0;
  let edgeCount = 0;
  let configSelected = false;

  const initView = async () => {
    initialized = true;
    const loadedData = (await d3.json(
      `${import.meta.env.BASE_URL}data/${modelFile}`
    )) as GraphData;

    const height = width;

    if (component) {
      myGraph = new Graph({
        component,
        data: loadedData,
        strengths,
        width,
        height
      });
    }

    nodeCount = loadedData.nodes.length;
    edgeCount = loadedData.links.length;
  };

  const flipConfigSelected = () => {
    configSelected = !configSelected;
  };

  onMount(() => {
    mounted = true;
  });

  $: !initialized && mounted && component && modelFile && initView();
</script>

<style lang="scss">
  @import 'Graph.scss';
</style>

<div
  class="graph-wrapper"
  style={`width: ${width}px; height: ${width}px;`}
  bind:this={component}
>
  <svg class="graph-svg" />

  <div class="graph-footer">
    {`${nodeCount} nodes, ${edgeCount} edges`}
  </div>

  <div
    class="config-button"
    class:selected={configSelected}
    on:click={() => {
      flipConfigSelected();
    }}
  >
    {@html iconSetting}
  </div>
  <div class="config-container" class:no-display={!configSelected}>
    <ConfigPanel height={width} {myGraph} {flipConfigSelected} />
  </div>
</div>
