// svelte/src/components/config-panel/ConfigPanel.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import type { Graph } from '../graph/Graph';
  import { initForceParameters } from './ConfigPanel';
  import type { ForceParameter } from './ConfigPanel';
  import d3 from '../../d3-imports';
  import iconClose from '../../images/icon-close.svg?raw';

  export let height: number;
  export let myGraph: Graph | null = null;
  export let flipConfigSelected: () => void = () => {};

  let component: HTMLElement | null = null;
  let initialized = false;
  let mounted = false;
  let forceParameters: ForceParameter[] | null = null;

  const initView = () => {
    if (myGraph) {
      initialized = true;

      // Construct the parameters
      forceParameters = initForceParameters(myGraph);
    }
  };

  onMount(() => {
    mounted = true;
  });

  $: !initialized && mounted && component && myGraph && initView();
</script>

<style lang="scss">
  @import 'ConfigPanel.scss';
</style>

<div
  class="parameter-wrapper"
  style={`max-height: ${Math.max(50, height - 30)}px;`}
  bind:this={component}
>
  <div class="parameter-title">
    <span>Force Parameters</span>
    <span class="svg-icon" on:click={() => flipConfigSelected()}
      >{@html iconClose}</span
    >
  </div>

  {#if forceParameters !== null}
    {#each forceParameters as parameter}
      <div class="parameter-item">
        <div class="parameter">
          <span class="parameter-name">{parameter.name}</span>
          <span class="parameter-value">{parameter.value}</span>
        </div>

        <input
          type="range"
          id={`${parameter.id}-slider`}
          class="slider"
          name={`${parameter.id}`}
          min={parameter.min}
          max={parameter.max}
          value={parameter.value}
          step={parameter.step}
          on:input={e => {
            parameter.value = parseFloat(e.currentTarget.value);
            parameter.updateStrength(parseFloat(e.currentTarget.value));
          }}
        />
      </div>
    {/each}
  {:else}
    <div class="parameter-item">Loading...</div>
  {/if}
</div>

// react-js/src/components/ConfigPanel/ConfigPanel.tsx
import React from 'react';
import './ConfigPanel.css'
import { initForceParameters } from './ConfigPanelTypes.ts';
import IconClose from '../../images/icon-close.tsx';

const ConfigPanel = ({ height, myGraph, flipConfigSelected }) => {
  const [forceParameters, setForceParameters] = React.useState(null);
  const [parameters, setParameters] = React.useState({});

  React.useEffect(() => {
    if (myGraph) {
      setForceParameters(initForceParameters(myGraph));
    }
  }, [myGraph])

  React.useEffect(() => {
      setParameters({})
      if (forceParameters) {
        forceParameters.forEach((parameter) => {
          setParameters({ ...parameters, [parameter.name]: parameter.value });
        })
      }
  }, [forceParameters, parameters])

  return (
      <div className="parameter-wrapper" style={{maxHeight: `${Math.max(50, height - 30)}px`}}>
        <div className="parameter-title">
          <span>Force Parameters</span>
          <span className="svg-icon" onClick={() => flipConfigSelected()}>
            <IconClose />
          </span>
        </div>
      {forceParameters && forceParameters.map((parameter) => (
        <div className="parameter-item" key={parameter.name}>
          <div className="parameter">
            <span className="parameter-name">{parameter.name}</span>
            <span className="parameter-value">{parameter.value}</span>
          </div>
          <input
            type="range"
            id={`${parameter.id}-slider`}
            className="slider"
            name={`${parameter.id}`}
            min={parameter.min}
            max={parameter.max}
            value={parameters[parameter.name]}
            step={parameter.step}
            onInput={e => {
              parameter.value = parseFloat(e.currentTarget.value);
              parameter.updateStrength(parseFloat(e.currentTarget.value));
              forceParameters.forEach((parameter) => {
                setParameters({ ...parameters, [parameter.name]: parameter.value });
              })
              parameters[parameter.name] = parseFloat(e.currentTarget.value);
            }
          }
          />
        </div>
      ))}
    </div>
  )
}

export default ConfigPanel;
